blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/dcyfr/cyberdrew-dev/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub Security Advisories.
