name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  # Harden default token permissions (least privilege)
  pull-requests: read

jobs:
  build-lint-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
  uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
  uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Audit production (fail on high)
        run: npm audit --omit=dev --audit-level=high

      - name: Audit all (report-only)
        run: |
          npm audit || true
